# Generated by Django 6.0.6 on 2026-06-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('tracking_number', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=80, unique=True)),
                ('flag', models.CharField(blank=True, help_text='Emoji flag, e.g. 🇺🇸', max_length=8)),
                ('rate_per_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_days', models.CharField(help_text='e.g. 5–7 days', max_length=30)),
                ('carriers', models.CharField(help_text='e.g. FedEx · DHL Express', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='RestrictedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=80)),
                ('item', models.CharField(max_length=160)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['country', 'item'],
            },
        ),
    ]
