# Generated by Django 6.0.6 on 2026-07-03 07:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_initial'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customs_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('1800.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate_per_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='tracking.parcel')),
            ],
        ),
        migrations.CreateModel(
            name='BoxCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='operations.box')),
            ],
        ),
        migrations.CreateModel(
            name='BoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.box')),
            ],
        ),
    ]
