# Generated by Django 6.0.6 on 2026-07-03 07:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_invoice_customs_tax_box_boxcharge_boxitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='additional_charges_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='rate_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
