# Generated by Django 5.2.9 on 2026-07-07 05:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_invoice_additional_charges_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxitem',
            name='unit_value_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
