# Generated by Django 5.2.9 on 2026-09-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_boxitem_unit_value_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FUEL', 'Fuel / Transport'), ('RENT', 'Rent'), ('SALARY', 'Salary'), ('HUB', 'HUB'), ('CARRIER', 'Carrier Charges'), ('SUPPLIES', 'Supplies'), ('OTHER', 'Other')], default='OTHER', max_length=12),
        ),
    ]
