# Generated by Django 6.0.6 on 2026-06-11 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('sender_name', models.CharField(max_length=120)),
                ('sender_phone', models.CharField(max_length=20)),
                ('sender_address', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('receiver_name', models.CharField(max_length=120)),
                ('receiver_phone', models.CharField(max_length=30)),
                ('receiver_address', models.CharField(max_length=255)),
                ('destination_country', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('REGISTERED', 'Parcel Registered'), ('PROCESSING', 'Parcel Processing'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=12)),
                ('carrier', models.CharField(blank=True, choices=[('FEDEX', 'FedEx'), ('DHL', 'DHL Express'), ('ARAMEX', 'Aramex'), ('SKYNET', 'SkyNet'), ('DPD', 'DPD')], max_length=10)),
                ('carrier_tracking_no', models.CharField(blank=True, max_length=60)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='operations.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Parcel Registered'), ('PROCESSING', 'Parcel Processing'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=12)),
                ('location', models.CharField(max_length=160)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.parcel')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
