# Generated by Django 6.0.6 on 2026-07-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('ORDER_CREATED', '📦 Order Created'), ('COLLECTED', '✅ Parcel Collected'), ('RECEIVED_BRANCH', '🏢 Received at Courier Spot Branch'), ('PROCESSED', '📋 Shipment Processed'), ('TRANSFERRED_HUB', '🚚 Transferred to Kathmandu Export Hub'), ('EXPORT_CUSTOMS', '🛃 Export Customs Clearance'), ('DEPARTED', '✈️ Departed from Nepal'), ('IN_TRANSIT', '🌍 In Transit'), ('ARRIVED_DEST', '🇬🇧 Arrived at Destination Country'), ('IMPORT_CUSTOMS', '🛃 Import Customs Clearance'), ('TRANSFERRED_LOCAL', '🚛 Transferred to Local Delivery Partner'), ('OUT_FOR_DELIVERY', '🚚 Out for Delivery'), ('DELIVERED', '✅ Delivered'), ('CANCELLED', 'Cancelled')], default='ORDER_CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='status',
            field=models.CharField(choices=[('ORDER_CREATED', '📦 Order Created'), ('COLLECTED', '✅ Parcel Collected'), ('RECEIVED_BRANCH', '🏢 Received at Courier Spot Branch'), ('PROCESSED', '📋 Shipment Processed'), ('TRANSFERRED_HUB', '🚚 Transferred to Kathmandu Export Hub'), ('EXPORT_CUSTOMS', '🛃 Export Customs Clearance'), ('DEPARTED', '✈️ Departed from Nepal'), ('IN_TRANSIT', '🌍 In Transit'), ('ARRIVED_DEST', '🇬🇧 Arrived at Destination Country'), ('IMPORT_CUSTOMS', '🛃 Import Customs Clearance'), ('TRANSFERRED_LOCAL', '🚛 Transferred to Local Delivery Partner'), ('OUT_FOR_DELIVERY', '🚚 Out for Delivery'), ('DELIVERED', '✅ Delivered'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
    ]
