# Generated by Django 5.2.9 on 2026-07-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_parcel_status_alter_trackingevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='draft_customs_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
