# Generated by Django 5.2.9 on 2026-09-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_parcel_status_alter_trackingevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
