# Generated by Django 5.2.9 on 2026-09-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_alter_parcel_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='carrier',
            field=models.CharField(blank=True, choices=[('FEDEX', 'FedEx'), ('DHL', 'DHL Express'), ('ARAMEX', 'Aramex'), ('DPD', 'DPD'), ('UPS', 'UPS'), ('LHR', 'LHR'), ('AMS', 'AMS')], max_length=10),
        ),
    ]
